---
- name: Login to Azure Container Registry
  containers.podman.podman_login:
    registry: "{{ acr_name }}.azurecr.io"
    username: "{{ lookup('env','ACR_USERNAME') }}"
    password: "{{ lookup('env','ACR_PASSWORD') }}"

- name: Pull nginx image
  containers.podman.podman_image:
    name: docker.io/library/nginx
    tag: latest
    pull: yes
    arch: amd64

- name: Push nginx image to ACR
  containers.podman.podman_image:
    name: docker.io/library/nginx
    tag: latest
    push: yes
    push_args:
      dest: "{{ acr_name }}.azurecr.io/nginx:casopractico2"

- name: Pull redis image
  containers.podman.podman_image:
    name: docker.io/library/redis
    tag: "6.0.8"
    pull: yes
    arch: amd64

- name: Push redis image to ACR
  containers.podman.podman_image:
    name: docker.io/library/redis
    tag: "6.0.8"
    push: yes
    push_args:
      dest: "{{ acr_name }}.azurecr.io/redis:6.0.8"

- name: Clone azure-voting-app repository
  ansible.builtin.git:
    repo: https://github.com/ptaritepui/azure-voting-app.git
    dest: /tmp/azure-voting-app
    version: master
    force: yes

- name: Fix Debian Buster EOL apt sources in Dockerfile
  ansible.builtin.lineinfile:
    path: /tmp/azure-voting-app/azure-vote/Dockerfile-for-app-service
    insertbefore: 'RUN  mkdir -p /home/LogFiles'
    line: "RUN sed -i -e 's/deb.debian.org/archive.debian.org/g' -e 's|security.debian.org/debian-security|archive.debian.org/debian-security|g' -e '/buster-updates/d' /etc/apt/sources.list"

- name: Build azure-vote-front image
  containers.podman.podman_image:
    name: azure-vote-front
    tag: latest
    path: /tmp/azure-voting-app/azure-vote
    build:
      file: /tmp/azure-voting-app/azure-vote/Dockerfile-for-app-service

- name: Push azure-vote-front image to ACR
  containers.podman.podman_image:
    name: azure-vote-front
    tag: latest
    push: yes
    push_args:
      dest: "{{ acr_name }}.azurecr.io/azure-vote-front:latest"
