- name: Create namespace
  kubernetes.core.k8s:
    state: present
    definition:
      apiVersion: v1
      kind: Namespace
      metadata:
        name: casopractico2

- name: Build dockerconfigjson
  set_fact:
    dockerconfigjson: "{{ {
      'auths': {
        (acr_name + '.azurecr.io'): {
          'username': lookup('env','ACR_USERNAME'),
          'password': lookup('env','ACR_PASSWORD'),
          'auth': (lookup('env','ACR_USERNAME') + ':' + lookup('env','ACR_PASSWORD')) | b64encode
        },
      }} | to_json | b64encode }}"

- name: Create ACR secret
  kubernetes.core.k8s:
    state: present
    definition:
      apiVersion: v1
      kind: Secret
      metadata:
        name: acr-secret
        namespace: casopractico2
      type: kubernetes.io/dockerconfigjson
      data:
        .dockerconfigjson: "{{ dockerconfigjson }}"

- name: Deploy resources to AKS
  kubernetes.core.k8s:
    state: present
    namespace: casopractico2
    src: "{{ role_path }}/files/{{ item }}"
  loop:
    - pvc.yaml
    - redis-deployment.yaml
    - front-deployment.yaml
    - service.yaml
    - redis-service.yaml
