flowchart TB

subgraph Azure Subscription

RG[Resource Group<br>rg-casopractico2]

VNET[Virtual Network]

SUBNET[Subnet]

NSG[Network Security Group]

NIC[Network Interface]

PIP[Public IP]

VM[Linux VM]

ACR[Azure Container Registry]

AKS[Azure Kubernetes Service]

end

RG --> VNET
VNET --> SUBNET
SUBNET --> NIC
NIC --> VM

NSG --> NIC
PIP --> NIC

RG --> ACR
RG --> AKS